name: formkit
description: A powerful form management library for Flutter inspired by React Formik
version: 1.0.0
homepage: https://github.com/yourusername/formkit
repository: https://github.com/yourusername/formkit
issue_tracker: https://github.com/yourusername/formkit/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0

topics:
  - forms
  - validation
  - state-management
  - flutter
  - dart

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: